export const state = {
  dataset: null,
  relatedDatasets: {},
  allAnchorDatasets: {},
  selectedCalendarAnchors: [],
  filteredTeams: [],
  selectedTeamKey: null,
  mode: "light",
};

export const els = {
  anchorNav: document.getElementById("anchor-nav"),
  brandName: document.querySelector(".brand-name"),
  mobileSidebarToggle: document.getElementById("mobile-sidebar-toggle"),
  mobileSidebarClose: document.getElementById("mobile-sidebar-close"),
  mobileSidebarBackdrop: document.getElementById("mobile-sidebar-backdrop"),
  sidebar: document.getElementById("app-sidebar"),
  sidebarAnchorSwitch: document.getElementById("sidebar-anchor-switch"),
  hero: document.getElementById("hero"),
  sidebarAnchorName: document.getElementById("sidebar-anchor-name"),
  homeNavButton: document.getElementById("home-nav-button"),
  backButton: document.getElementById("back-button"),
  modeToggle: document.getElementById("mode-toggle"),
  teamSearch: document.getElementById("team-search"),
  upcomingTeamList: document.getElementById("upcoming-team-list"),
  recentTeamList: document.getElementById("recent-team-list"),
  allTeamList: document.getElementById("all-team-list"),
  matchSearch: document.getElementById("match-search"),
  datasetMeta: document.getElementById("dataset-meta"),
  heroEyebrow: document.getElementById("hero-eyebrow"),
  teamClub: document.getElementById("team-club"),
  teamTitle: document.getElementById("team-title"),
  teamSubtitle: document.getElementById("team-subtitle"),
  teamGotsportLink: document.getElementById("team-gotsport-link"),
  teamHomeLink: document.getElementById("team-home-link"),
  heroMeta: document.getElementById("hero-meta"),
  summaryGrid: document.getElementById("summary-grid"),
  comparePanel: document.getElementById("compare-panel"),
  compareSummary: document.getElementById("compare-summary"),
  calendarSpotlightPanel: document.getElementById("calendar-spotlight-panel"),
  calendarFilterPills: document.getElementById("calendar-filter-pills"),
  homePanel: document.getElementById("home-panel"),
  calendarPanel: document.getElementById("calendar-panel"),
  homePanelTitle: document.getElementById("home-panel-title"),
  homePanelCopy: document.getElementById("home-panel-copy"),
  homeUpcomingBody: document.getElementById("home-upcoming-body"),
  homeRecentBody: document.getElementById("home-recent-body"),
  calendarRangeLabel: document.getElementById("calendar-range-label"),
  calendarCherryGrid: document.getElementById("calendar-cherry-grid"),
  calendarSleightonGrid: document.getElementById("calendar-sleighton-grid"),
  calendarMatchesBody: document.getElementById("calendar-matches-body"),
  calendarHomeGamesGrid: document.getElementById("calendar-home-games-grid"),
  matchesPanel: document.getElementById("matches-panel"),
  historicalSectionTitle: document.getElementById("historical-section-title"),
  historicalMatchesBody: document.getElementById("historical-matches-body"),
  upcomingMatchesBody: document.getElementById("upcoming-matches-body"),
};
